Add highlight to event card when time come
cpe-kmutt-student/bangmod-hackathon-2023 pull request #71
Opened 2022-10-17 19:01 UTC by XiaoXuxxxx

My time has come

2022-10-17 19:02 UTC, XiaoXuxxxx commented
it's work. trust me bro

2022-10-17 19:07 UTC, riflowth requested changes

2022-10-17 19:07 UTC, riflowth commented on apps/registration/src/components/HorizontalTimeline.tsx
> +  const isCurrentEvent = new Date(startTime) <= new Date() && new Date() <= new Date(endTime);
`new Date()` should be initiated once

2022-10-17 19:07 UTC, riflowth commented
@XiaoXuxxxx Should we update the highlight realtime?

2022-10-17 19:18 UTC, XiaoXuxxxx commented on apps/registration/src/components/HorizontalTimeline.tsx
> +  const isCurrentEvent = new Date(startTime) <= new Date() && new Date() <= new Date(endTime);
done bro

2022-10-21 04:08 UTC, XiaoXuxxxx commented on apps/registration/src/components/HorizontalTimeline.tsx
> +  const isCurrentEvent = new Date(startTime) <= new Date() && new Date() <= new Date(endTime);
Forget to resolve, lol

2022-10-21 04:09 UTC, riflowth approved these changes

2022-10-21 04:09 UTC, merged